---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  vars:
    database:
      container_name: "hub_db"
      container_version: postgres:9.6
      volume_name: "/tmp/molecule/database"
    network_name: "hub_network"

  pre_tasks:
  - name: Start Database
    docker_container:
      name: "{{ database.container_name }}"
      image: "{{ database.container_version }}"
      restart_policy: unless-stopped
      env:
        POSTGRES_HOST_AUTH_METHOD: "trust"
      volumes:
        - "{{ database.volume_name }}:/var/lib/postgresql/data"
      networks_cli_compatible: true
      # networks:
      #   - name: "{{ network_name}}"
      #     aliases:
      #       - db