---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: moleule-docker
    image: debian:stretch-slim
provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
    prepare: prepare.yml
  lint:
    name: ansible-lint
    options:
      exclude:
        - $HOME/.ansible/roles
verifier:
  name: testinfra
  lint:
    name: flake8
